// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkrE1TxyOZo-BqQaCxe7XtAXGquFFf5bQ',
    appId: '1:783783765577:web:e5bd6545033c9882fa0198',
    messagingSenderId: '783783765577',
    projectId: 'tourismproject-21995',
    authDomain: 'tourismproject-21995.firebaseapp.com',
    storageBucket: 'tourismproject-21995.appspot.com',
    measurementId: 'G-CMX06S9V9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByp0h5BD0rqM1fwX8Hwim21XpPT-NGYyY',
    appId: '1:783783765577:android:2b08623f37e525c3fa0198',
    messagingSenderId: '783783765577',
    projectId: 'tourismproject-21995',
    storageBucket: 'tourismproject-21995.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNhhSaYLhzrLqWAFzqSnH7mRdH4LbwQj4',
    appId: '1:783783765577:ios:50c12ad88abb789dfa0198',
    messagingSenderId: '783783765577',
    projectId: 'tourismproject-21995',
    storageBucket: 'tourismproject-21995.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNhhSaYLhzrLqWAFzqSnH7mRdH4LbwQj4',
    appId: '1:783783765577:ios:50c12ad88abb789dfa0198',
    messagingSenderId: '783783765577',
    projectId: 'tourismproject-21995',
    storageBucket: 'tourismproject-21995.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkrE1TxyOZo-BqQaCxe7XtAXGquFFf5bQ',
    appId: '1:783783765577:web:08308d9e76f1509ffa0198',
    messagingSenderId: '783783765577',
    projectId: 'tourismproject-21995',
    authDomain: 'tourismproject-21995.firebaseapp.com',
    storageBucket: 'tourismproject-21995.appspot.com',
    measurementId: 'G-PMSWMLMWR0',
  );
}
